# Set deep sleep to 30 minutes
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000
CONFIG_BT_MAX_CONN=3
CONFIG_BT_MAX_PAIRED=3

# Better compatibility with iPadOS
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y
